spring.application.name=QuanLyChiTieu
# C?u hình c?ng ch?y ?ng d?ng (M?c ??nh là 8080)
server.port=8080

# C?U HÌNH K?T N?I POSTGRESQL
# Cú pháp k?t n?i: jdbc:postgresql://localhost:5432/ten_database_cua_ban
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=Vucongtien123

# Khai báo Driver s? d?ng cho PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# C?U HÌNH HIBERNATE / JPA
# ??nh ngh?a "ngôn ng?" SQL mà Hibernate s? sinh ra (Dành riêng cho Postgres)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# T? ??ng t?o/c?p nh?t b?ng d?a vào code Java
spring.jpa.hibernate.ddl-auto=update

# In các câu l?nh SQL ra c?a s? Console ?? ti?n theo dõi
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true